name: Commit Day Moment

on:
  schedule:
    - cron: "0 7 * * *" # Roda às 4h da manhã no Brasil (UTC-3)
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update GitHub Stats
        uses: thanhhaudev/github-stats@v1.3.1
        with:
          COMMIT_USER_NAME: DrkCde15
          COMMIT_USER_EMAIL: jcesarsantana215@gmail.com
